In [2]:
import pandas as pd

In [3]:
air_quality_2 = pd.read_csv("PM25_C1.csv")
air_quality_2 = air_quality_2.drop(columns=["Unnamed: 0", "index"])
air_quality_2.head(5)

,WHO Country Name,City or Locality,Measurement Year,PM2.5 (μg/m3),PM25 temporal coverage (%)
0,Afghanistan,Kabul,2019,119.77,18.0
1,Albania,Durres,2016,14.32,NaN
2,Albania,Korce,2015,30.34,NaN
3,Albania,Korce,2016,28.64,NaN
4,Albania,Vlore,2019,10.32,NaN

In [4]:
cities = air_quality_2['City or Locality'].unique()
cities
# cities = ['Adelaide']

array(['Kabul', 'Durres', 'Korce', ..., 'Uthungulu', 'Waterberg',
       'West Coast'], dtype=object)

In [33]:
df_test = pd.DataFrame(data={"WHO Country Name": [], "City or Locality": [], "Measurement Year": [], "PM2.5 (μg/m3)": [], "PM25 temporal coverage (%)": []})
for city in cities:
    df_current_city = air_quality_2[air_quality_2['City or Locality'] == city]
    replace_value = df_current_city['PM25 temporal coverage (%)'].mean()
    df_current_city = df_current_city.fillna(value = float(replace_value))
    df_test = pd.concat([df_test, df_current_city])

In [34]:
df_test["PM25 temporal coverage (%)"] = df_test["PM25 temporal coverage (%)"].astype(float).round(2)
df_test.head(10)

,WHO Country Name,City or Locality,Measurement Year,PM2.5 (μg/m3),PM25 temporal coverage (%)
0,Afghanistan,Kabul,2019.0,119.77,18.00
1,Albania,Durres,2016.0,14.32,NaN
2,Albania,Korce,2015.0,30.34,NaN
3,Albania,Korce,2016.0,28.64,NaN
4,Albania,Vlore,2019.0,10.32,NaN
5,Albania,Vrith,2015.0,13.24,NaN
6,United Arab Emirates,Abu Dhabi,2017.0,32.79,88.65
7,United Arab Emirates,Abu Dhabi,2018.0,49.13,88.29
8,United Arab Emirates,Abu Dhabi,2019.0,44.40,89.00
9,United Arab Emirates,Dubai,2018.0,53.93,99.49

In [35]:
df_test.to_csv("clean_test.csv")

In [36]:
df_test.head(10)

,WHO Country Name,City or Locality,Measurement Year,PM2.5 (μg/m3),PM25 temporal coverage (%)
0,Afghanistan,Kabul,2019.0,119.77,18.00
1,Albania,Durres,2016.0,14.32,NaN
2,Albania,Korce,2015.0,30.34,NaN
3,Albania,Korce,2016.0,28.64,NaN
4,Albania,Vlore,2019.0,10.32,NaN
5,Albania,Vrith,2015.0,13.24,NaN
6,United Arab Emirates,Abu Dhabi,2017.0,32.79,88.65
7,United Arab Emirates,Abu Dhabi,2018.0,49.13,88.29
8,United Arab Emirates,Abu Dhabi,2019.0,44.40,89.00
9,United Arab Emirates,Dubai,2018.0,53.93,99.49